var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0}),exports.Toolbar=void 0,exports.registerToolbarComponent=function(e,t){_[e]=t};const t=e(require("react")),o=require("mobx-react-lite"),r=require("@blueprintjs/core"),l=e(require("../utils/styled")),n=require("../utils/screen"),a=require("./history-buttons"),i=require("./text-toolbar"),u=require("./html-toolbar"),s=require("./image-toolbar"),d=require("./svg-toolbar"),c=require("./line-toolbar"),m=require("./video-toolbar"),b=require("./figure-toolbar"),p=require("./gif-toolbar"),f=require("./many-toolbar"),y=require("./page-toolbar"),v=require("./download-button"),g=require("./duplicate-button"),q=require("./remove-button"),E=require("./lock-button"),h=require("./position-picker"),x=require("./opacity-picker"),T=require("./admin-button"),w=require("./group-button"),k=require("../utils/flags"),B=require("./copy-style"),_={text:i.TextToolbar,image:s.ImageToolbar,svg:d.SvgToolbar,many:f.ManyToolbar,line:c.LineToolbar,video:m.VideoToolbar,figure:b.FigureToolbar,gif:p.GifToolbar,page:y.PageToolbar},O=(0,l.default)("div")`
  white-space: nowrap;

  /* Add special style for a button with text inside, to make sure it has good with */
  & .bp5-button:has(.bp5-button-text) {
    min-width: max-content;
  }

  ${(0,n.mobileStyle)("\n    max-width: 100vw;\n    overflow-x: auto;\n    overflow-y: hidden;\n  ")}
`,P=(0,l.default)("div")`
  width: 100%;
  height: 100%;
  ${(0,n.mobileStyle)("\n    display: flex;\n  ")}
`;exports.Toolbar=(0,o.observer)((({store:e,downloadButtonEnabled:o,components:l={}})=>{const n=1===new Set(e.selectedElements.map((e=>e.type))).size,i=1===e.selectedElements.length,s=e.selectedElements[0],d=e.selectedElements.every((e=>e.styleEditable));let c=d&&i&&_[s.type];n?c=_[s.type]:e.selectedElements.length>1&&(c=_.many),0===e.selectedElements.length&&(c=_.page),i&&"text"===s.type&&k.flags.htmlRenderEnabled&&(c=u.HtmlToolbar);const m=i&&s._cropModeEnabled,b=t.default.useRef(l);(Object.keys(l).some((e=>l[e]!==b.current[e]))||Object.keys(b.current).some((e=>!(e in l))))&&(b.current=Object.assign({},l));const p=b.current,f=(null==p?void 0:p.ActionControls)||(o?v.DownloadButton:null),y=(null==p?void 0:p.Position)||h.PositionPicker,S=(null==p?void 0:p.Opacity)||x.OpacityPicker,j=(null==p?void 0:p.Lock)||E.LockButton,A=(null==p?void 0:p.Duplicate)||g.DuplicateButton,D=(null==p?void 0:p.Remove)||q.RemoveButton,G=(null==p?void 0:p.Group)||w.GroupButton,R=(null==p?void 0:p.History)||a.HistoryButtons,C=(null==p?void 0:p.Admin)||T.AdminButton,H=(null==p?void 0:p.CopyStyle)||B.CopyStyleButton;return t.default.createElement(O,{className:"bp5-navbar polotno-toolbar"},t.default.createElement(P,null,!m&&t.default.createElement(R,{store:e}),c&&d&&t.default.createElement(c,{store:e,components:p}),!m&&t.default.createElement(r.Navbar.Group,{align:r.Alignment.RIGHT},"admin"===e.role&&t.default.createElement(C,{store:e}),t.default.createElement(G,{store:e}),t.default.createElement(y,{store:e}),d&&t.default.createElement(S,{store:e}),t.default.createElement(j,{store:e}),t.default.createElement(A,{store:e}),t.default.createElement(D,{store:e}),t.default.createElement(H,{store:e}),f&&t.default.createElement(t.default.Fragment,null,t.default.createElement(r.Divider,{style:{height:"100%",margin:"0 15px"}}),t.default.createElement(f,{store:e})))))})),exports.default=exports.Toolbar;