import { ShapeType } from '../model/shape-model';
export declare const useColor: (element: ShapeType, value?: any, propName?: string) => {
    [x: string]: any;
    fillLinearGradientStartPointX?: undefined;
    fillLinearGradientStartPointY?: undefined;
    fillLinearGradientColorStops?: undefined;
    fillLinearGradientEndPointX?: undefined;
    fillLinearGradientEndPointY?: undefined;
    fill?: undefined;
    fillPriority?: undefined;
    strokeLinearGradientStartPointX?: undefined;
    strokeLinearGradientStartPointY?: undefined;
    strokeLinearGradientColorStops?: undefined;
    strokeLinearGradientEndPointX?: undefined;
    strokeLinearGradientEndPointY?: undefined;
} | {
    fillLinearGradientStartPointX: number;
    fillLinearGradientStartPointY: number;
    fillLinearGradientColorStops: any[];
    fillLinearGradientEndPointX: number;
    fillLinearGradientEndPointY: number;
    fill: any;
    fillPriority: string;
    strokeLinearGradientStartPointX?: undefined;
    strokeLinearGradientStartPointY?: undefined;
    strokeLinearGradientColorStops?: undefined;
    strokeLinearGradientEndPointX?: undefined;
    strokeLinearGradientEndPointY?: undefined;
} | {
    strokeLinearGradientStartPointX: number;
    strokeLinearGradientStartPointY: number;
    strokeLinearGradientColorStops: any[];
    strokeLinearGradientEndPointX: number;
    strokeLinearGradientEndPointY: number;
    fillLinearGradientStartPointX?: undefined;
    fillLinearGradientStartPointY?: undefined;
    fillLinearGradientColorStops?: undefined;
    fillLinearGradientEndPointX?: undefined;
    fillLinearGradientEndPointY?: undefined;
    fill?: undefined;
    fillPriority?: undefined;
};
