import React from 'react';
import { PopoverPosition } from '@blueprintjs/core';
import { StoreType } from '../model/store';
export declare const DEFAULT_COLORS: string[];
export declare const getUsedColors: (store: StoreType) => string[];
type Props = {
    size?: number;
    onChange: (color: string) => void;
    onOpen?: () => void;
    onClose?: () => void;
    value: string;
    store: StoreType;
    gradientEnabled?: boolean;
    style?: any;
    children?: any;
    position?: PopoverPosition;
};
declare let getColorsPreset: (store: StoreType) => string[];
export declare function setColorsPresetFunc(func: typeof getColorsPreset): void;
export declare const ColorPicker: ({ value, onChange, size, store, gradientEnabled, children, style, position, onOpen, onClose, }: Props) => React.JSX.Element;
export default ColorPicker;
